### PR TITLE
Update to include more endpoints

### PR DESCRIPTION
**Pull request by phoenixy1**
(this is alex)

Added several endpoints, including Bank Transfers endpoints and the new /link/token/get and /sandbox/processor_token/create endpoint, based on their export from the openapi file.

This is my first time editing this file so I would appreciate a check to make sure I didn't break anything.

Thanks!

### CODE REVIEW

**Comment by Mendoza920** [comment]
Honestly, I have no idea on how to go about this.
I feel lost for that reason.

**Comment by Mendoza920** [comment]
My phone got confiscated and I have nothing.

**Review by daniellacoste — APPROVED** [review]
🥌 

I don't know if I have stamp permissions in this repo (@edwinychu for sure does), but I'll try 😄

**Comment by Mendoza920** [comment]
Help me. I don’t know what to do

**Pull request merged**
