### PR TITLE
add Identity Verification and Monitor

### PR DESCRIPTION
**Pull request by achen88**

### CODE REVIEW

**Review by phoenixy1 — DISMISSED** [review]
lgtm with some non-blocking caveats:

A couple of endpoints are missing examples.

I notice you're not using {{variables}} for stuff like template_id and entity screening. Based on my understanding of how the API works, I think that what you are doing is correct/fine (these variables only need to be set if you're getting output from one endpoint that you're passing directly into another endpoint, similar to how access tokens work in Plaid endpoints) but if I misunderstood you might want to change this.

**Comment by achen88** [comment]
There are _some_ ids that are shared/generated from a few of these endpoints, and I will make the appropriate changes. However, there are also a few ids that must be generated through the Cognito dashboard (the flow `template_id` for Identity Verification, and `entity_watchlist_program_id` and `watchlist_program_id` for Monitor) that I will be leaving.

I also wanted to call out that there are 4 endpoints missing OK example response bodies due to blocking bugs. I think the docs will be okay, but do you have preference over what to do here?

- /watchlist_screening/entity/list
- /watchlist_screening/individual/list
- /watchlist_screening/entity/review/create
- /watchlist_screening/individual/review/create

**Comment by phoenixy1** [comment]
It's ok to just not have the example response bodies!

**Review by phoenixy1 — APPROVED** [review]
🎉

**Pull request merged**
